### ISSUE TITLE
Implement User Authentication Using Django's Authentication System

### ISSUE THREAD

**Issue by JSchwerberg** [djangolearners/forum#4]
Django's Authentication documentation can be found [here](https://docs.djangoproject.com/en/1.9/topics/auth/).

**Comment by d0ntreadthis** [comment]
issue #6

**Comment by stephsamson** [comment]
[PR Approved](https://github.com/djangolearners/forum/pull/6)

**Comment by anweshknayak** [comment]
Is this still active ?

**Comment by d0ntreadthis** [comment]
@anweshknayak I don't think so, no one's been working on it. I was recently thinking about working on it again though.

**Comment by JSchwerberg** [comment]
This specific issue has already been closed, and merged.  There hasn't been any activity on the repository, but I'm willing to check out PRs and issues.
