### ISSUE TITLE
Tie comments, threads, etc to user accounts

### ISSUE THREAD

**Issue by JSchwerberg** [djangolearners/forum#5]
All threads, comments, etc should be created by, and tied to, a user.

**Comment by JSchwerberg** [comment]
Blocked by #4

**Comment by d0ntreadthis** [comment]
issue #6

**Comment by stephsamson** [comment]
@d0ntreadthis Cool, thanks for the PR, will review it tonight!

**Comment by stephsamson** [comment]
[PR Approved](https://github.com/djangolearners/forum/pull/6)
